### ISSUE TITLE
Option to allow enabling cdn on lb backend

### ISSUE THREAD

**Issue by night-gold** [GoogleCloudPlatform/terraform-google-lb-http#11]
Hi,

I was working with the module and was trying to activate the cdn option that is available in the **google_compute_backend_service** resource.

I forked the repo, as I was needing it, here: https://github.com/night-gold/terraform-google-lb-http. 

I'll be waiting for your response before trying to do the pull request.

**Comment by danisla** [comment]
Fixed with #26
