### ISSUE TITLE
Resource google_compute_firewall.default-hc has two "count" arguments

### ISSUE THREAD

**Issue by apparentlymart** [GoogleCloudPlatform/terraform-google-lb-http#7]
https://github.com/GoogleCloudPlatform/terraform-google-lb-http/blob/b82fc47a848c92e0bbd45d874c2dd6669d200b32/main.tf#L91-L104

This resource has two `count` arguments defined. It seems that as of Terraform 0.11 this is silently ignored, with Terraform ignoring one of the specifications. A forthcoming Terraform release will make this a real error, as a usability improvement:

```
Error: Attribute redefined

  on main.tf line 94:
  94:   count         = "${length(var.backend_params)}"

The attribute "count" was already defined at main.tf:92,3-8. Each attribute may be defined only once.
```

Since this resource is using `count.index` with both `var.firewall_networks` and `var.backend_params`, I'm not sure which one was actually intended here.

**Comment by baileymooreatx** [comment]
I concur. To work around it until it's fixed, I was able to use fixed index 0 for the network because I'm only using one network.

**Comment by danisla** [comment]
See issue #27 where I comment on a potential solution to this.
